/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturaunt.gui;

/**
 *
 * @author Admin
 */
public class Desserts extends javax.swing.JPanel {

    /**
     * Creates new form Desserts
     */
    public Desserts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sides = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CookieB = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        IceCB = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        ApplePB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        DonutB = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        MuffinB = new javax.swing.JTextPane();
        BackToMenu = new javax.swing.JButton();
        DonutCombo = new javax.swing.JComboBox<>();
        CookieCombo = new javax.swing.JComboBox<>();
        IceCCombo = new javax.swing.JComboBox<>();
        ApplePCombo = new javax.swing.JComboBox<>();
        MuffinCombo = new javax.swing.JComboBox<>();

        Sides.setFont(new java.awt.Font("The Next Font", 0, 48)); // NOI18N
        Sides.setText("Dessert");

        CookieB.setEditable(false);
        CookieB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CookieB.setText("        1/2\n     Pounder\n      €4.00");
        CookieB.setToolTipText("hello");
        jScrollPane1.setViewportView(CookieB);

        IceCB.setEditable(false);
        IceCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IceCB.setText("        1/2\n     Pounder\n      €4.00");
        IceCB.setToolTipText("hello");
        jScrollPane2.setViewportView(IceCB);

        ApplePB.setEditable(false);
        ApplePB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ApplePB.setText("        1/2\n     Pounder\n      €4.00");
        ApplePB.setToolTipText("hello");
        jScrollPane3.setViewportView(ApplePB);

        DonutB.setEditable(false);
        DonutB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DonutB.setText("        1/2\n     Pounder\n      €4.00");
        DonutB.setToolTipText("hello");
        jScrollPane4.setViewportView(DonutB);

        MuffinB.setEditable(false);
        MuffinB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MuffinB.setText("        1/2\n     Pounder\n      €4.00");
        MuffinB.setToolTipText("hello");
        jScrollPane5.setViewportView(MuffinB);

        BackToMenu.setText("BACK");

        DonutCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        DonutCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonutComboActionPerformed(evt);
            }
        });

        CookieCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        CookieCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CookieComboActionPerformed(evt);
            }
        });

        IceCCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        IceCCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceCComboActionPerformed(evt);
            }
        });

        ApplePCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ApplePCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplePComboActionPerformed(evt);
            }
        });

        MuffinCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        MuffinCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuffinComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(Sides))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApplePCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CookieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IceCCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonutCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuffinCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Sides)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(CookieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(IceCCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(ApplePCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(DonutCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(MuffinCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DonutComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonutComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonutComboActionPerformed

    private void CookieComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CookieComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CookieComboActionPerformed

    private void IceCComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceCComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IceCComboActionPerformed

    private void ApplePComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplePComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApplePComboActionPerformed

    private void MuffinComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuffinComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuffinComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ApplePB;
    private javax.swing.JComboBox<String> ApplePCombo;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JTextPane CookieB;
    private javax.swing.JComboBox<String> CookieCombo;
    private javax.swing.JTextPane DonutB;
    private javax.swing.JComboBox<String> DonutCombo;
    private javax.swing.JTextPane IceCB;
    private javax.swing.JComboBox<String> IceCCombo;
    private javax.swing.JTextPane MuffinB;
    private javax.swing.JComboBox<String> MuffinCombo;
    private javax.swing.JLabel Sides;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
