/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturaunt.gui;

/**
 *
 * @author Admin
 */
public class Drinks extends javax.swing.JPanel {

    /**
     * Creates new form Drinks
     */
    public Drinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CokeB = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        FantaB = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        SevenupB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        DCokeB = new javax.swing.JTextPane();
        CokeCombo = new javax.swing.JComboBox<>();
        FantaCombo = new javax.swing.JComboBox<>();
        SevenupCombo = new javax.swing.JComboBox<>();
        DCokeCombo = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        CMilkB = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        WaterB = new javax.swing.JTextPane();
        WaterCombo = new javax.swing.JComboBox<>();
        SMilkCombo = new javax.swing.JComboBox<>();
        CMilkCombo = new javax.swing.JComboBox<>();
        VMilkCombo = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        SMilkB = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        VMilkB = new javax.swing.JTextPane();
        BackToMenu = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("The Next Font", 0, 48)); // NOI18N
        jLabel1.setText("Drinks");

        CokeB.setEditable(false);
        CokeB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CokeB.setText("    Coke    \n    €2.00");
        CokeB.setToolTipText("hello");
        jScrollPane1.setViewportView(CokeB);

        FantaB.setEditable(false);
        FantaB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FantaB.setText("    Fanta\n    €2.00");
        FantaB.setToolTipText("hello");
        jScrollPane2.setViewportView(FantaB);

        SevenupB.setEditable(false);
        SevenupB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SevenupB.setText("     7Up\n    €2.00");
        SevenupB.setToolTipText("hello");
        jScrollPane3.setViewportView(SevenupB);

        DCokeB.setEditable(false);
        DCokeB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DCokeB.setText(" Diet Coke\n    €2.00");
        DCokeB.setToolTipText("hello");
        jScrollPane4.setViewportView(DCokeB);

        CokeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        CokeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CokeComboActionPerformed(evt);
            }
        });

        FantaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        FantaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FantaComboActionPerformed(evt);
            }
        });

        SevenupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        SevenupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenupComboActionPerformed(evt);
            }
        });

        DCokeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        DCokeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCokeComboActionPerformed(evt);
            }
        });

        CMilkB.setEditable(false);
        CMilkB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CMilkB.setText("    Chocolate \n    Milkshake\n      €2.80");
        CMilkB.setToolTipText("hello");
        jScrollPane5.setViewportView(CMilkB);

        WaterB.setEditable(false);
        WaterB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WaterB.setText("    Water\n    €1.00");
        WaterB.setToolTipText("hello");
        jScrollPane6.setViewportView(WaterB);

        WaterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        WaterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterComboActionPerformed(evt);
            }
        });

        SMilkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        SMilkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMilkComboActionPerformed(evt);
            }
        });

        CMilkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        CMilkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMilkComboActionPerformed(evt);
            }
        });

        VMilkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        VMilkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VMilkComboActionPerformed(evt);
            }
        });

        SMilkB.setEditable(false);
        SMilkB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SMilkB.setText("   Strawberry \n    Milkshake\n      €2.80");
        SMilkB.setToolTipText("hello");
        jScrollPane9.setViewportView(SMilkB);

        VMilkB.setEditable(false);
        VMilkB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VMilkB.setText("      Vanilla \n    Milkshake\n      €2.80");
        VMilkB.setToolTipText("hello");
        jScrollPane10.setViewportView(VMilkB);

        BackToMenu.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DCokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SevenupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(FantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(SevenupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(DCokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(WaterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(SMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(CMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(VMilkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CokeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CokeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CokeComboActionPerformed

    private void FantaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FantaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FantaComboActionPerformed

    private void SevenupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenupComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SevenupComboActionPerformed

    private void DCokeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCokeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCokeComboActionPerformed

    private void WaterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaterComboActionPerformed

    private void SMilkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMilkComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SMilkComboActionPerformed

    private void CMilkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMilkComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMilkComboActionPerformed

    private void VMilkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VMilkComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VMilkComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenu;
    private javax.swing.JTextPane CMilkB;
    private javax.swing.JComboBox<String> CMilkCombo;
    private javax.swing.JTextPane CokeB;
    private javax.swing.JComboBox<String> CokeCombo;
    private javax.swing.JTextPane DCokeB;
    private javax.swing.JComboBox<String> DCokeCombo;
    private javax.swing.JTextPane FantaB;
    private javax.swing.JComboBox<String> FantaCombo;
    private javax.swing.JTextPane SMilkB;
    private javax.swing.JComboBox<String> SMilkCombo;
    private javax.swing.JTextPane SevenupB;
    private javax.swing.JComboBox<String> SevenupCombo;
    private javax.swing.JTextPane VMilkB;
    private javax.swing.JComboBox<String> VMilkCombo;
    private javax.swing.JTextPane WaterB;
    private javax.swing.JComboBox<String> WaterCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
