/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturaunt.gui;

/**
 *
 * @author Admin
 */
public class Mains extends javax.swing.JPanel {

    /**
     * Creates new form Mains
     */
    public Mains() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HalfPB = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuarterPB = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        VBurgerB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ChicBB = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ChicFillB = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        HotDogB = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        ChicNugB = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        ChicWrapB = new javax.swing.JTextPane();
        ChicBCombo = new javax.swing.JComboBox<>();
        VeggieBCombo = new javax.swing.JComboBox<>();
        QuarterPCombo = new javax.swing.JComboBox<>();
        HalfPCombo = new javax.swing.JComboBox<>();
        HotDogCombo = new javax.swing.JComboBox<>();
        ChicNugCombo = new javax.swing.JComboBox<>();
        ChicWrapCombo = new javax.swing.JComboBox<>();
        ChicFillCombo = new javax.swing.JComboBox<>();
        BackToMenu = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("The Next Font", 0, 48)); // NOI18N
        jLabel1.setText("Mains");

        HalfPB.setEditable(false);
        HalfPB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HalfPB.setText("        1/2\n     Pounder\n      €4.00");
        HalfPB.setToolTipText("hello");
        jScrollPane1.setViewportView(HalfPB);

        QuarterPB.setEditable(false);
        QuarterPB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QuarterPB.setText("       1/4\n     Pounder\n      €3.50");
        QuarterPB.setToolTipText("hello");
        jScrollPane2.setViewportView(QuarterPB);

        VBurgerB.setEditable(false);
        VBurgerB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VBurgerB.setText("      Veggie\n      Burger\n      €3.00");
        VBurgerB.setToolTipText("hello");
        jScrollPane3.setViewportView(VBurgerB);

        ChicBB.setEditable(false);
        ChicBB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChicBB.setText("Chicken\nBurger\n€3.00");
        ChicBB.setToolTipText("hello");
        jScrollPane4.setViewportView(ChicBB);

        ChicFillB.setEditable(false);
        ChicFillB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChicFillB.setText("Chic Fill\nburger 4.50");
        ChicFillB.setToolTipText("hello");
        jScrollPane5.setViewportView(ChicFillB);

        HotDogB.setEditable(false);
        HotDogB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotDogB.setText("ht dog\n3.00");
        HotDogB.setToolTipText("hello");
        jScrollPane6.setViewportView(HotDogB);

        ChicNugB.setEditable(false);
        ChicNugB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChicNugB.setText("chic\nnugs €3.0");
        ChicNugB.setToolTipText("hello");
        jScrollPane7.setViewportView(ChicNugB);

        ChicWrapB.setEditable(false);
        ChicWrapB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChicWrapB.setText("chic\nwrap\n3.50");
        ChicWrapB.setToolTipText("hello");
        jScrollPane8.setViewportView(ChicWrapB);

        ChicBCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ChicBCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicBComboActionPerformed(evt);
            }
        });

        VeggieBCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        VeggieBCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeggieBComboActionPerformed(evt);
            }
        });

        QuarterPCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        QuarterPCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuarterPComboActionPerformed(evt);
            }
        });

        HalfPCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        HalfPCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HalfPComboActionPerformed(evt);
            }
        });

        HotDogCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        HotDogCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotDogComboActionPerformed(evt);
            }
        });

        ChicNugCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ChicNugCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicNugComboActionPerformed(evt);
            }
        });

        ChicWrapCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ChicWrapCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicWrapComboActionPerformed(evt);
            }
        });

        ChicFillCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ChicFillCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicFillComboActionPerformed(evt);
            }
        });

        BackToMenu.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChicBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuarterPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HalfPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VeggieBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChicFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChicWrapCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HotDogCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChicNugCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HalfPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ChicFillCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(QuarterPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ChicWrapCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(VeggieBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ChicNugCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChicBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(HotDogCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChicBComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicBComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChicBComboActionPerformed

    private void VeggieBComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeggieBComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeggieBComboActionPerformed

    private void QuarterPComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuarterPComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuarterPComboActionPerformed

    private void HalfPComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HalfPComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HalfPComboActionPerformed

    private void HotDogComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotDogComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HotDogComboActionPerformed

    private void ChicNugComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicNugComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChicNugComboActionPerformed

    private void ChicWrapComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicWrapComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChicWrapComboActionPerformed

    private void ChicFillComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicFillComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChicFillComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenu;
    private javax.swing.JTextPane ChicBB;
    private javax.swing.JComboBox<String> ChicBCombo;
    private javax.swing.JTextPane ChicFillB;
    private javax.swing.JComboBox<String> ChicFillCombo;
    private javax.swing.JTextPane ChicNugB;
    private javax.swing.JComboBox<String> ChicNugCombo;
    private javax.swing.JTextPane ChicWrapB;
    private javax.swing.JComboBox<String> ChicWrapCombo;
    private javax.swing.JTextPane HalfPB;
    private javax.swing.JComboBox<String> HalfPCombo;
    private javax.swing.JTextPane HotDogB;
    private javax.swing.JComboBox<String> HotDogCombo;
    private javax.swing.JTextPane QuarterPB;
    private javax.swing.JComboBox<String> QuarterPCombo;
    private javax.swing.JTextPane VBurgerB;
    private javax.swing.JComboBox<String> VeggieBCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
